### ISSUE TITLE
Security-Issue_archlinux-2023.04.15-x86_64.iso

### ISSUE THREAD

**Issue by Rockets31** [arch-linux-calamares-installer/alci-iso-zen#1]
Hi,
you got a lot of repos here on github and I hope it is the correct branch... I was testing ACLI-zen-cinnamon-DE (?!) [archlinux-2023.04.15-x86_64.iso]. The installer puts a NOPASSWD-file  "/etc/sudoers.d/g_wheel". So you got root-privileges without getting asked for password...
Greetings 
Sebastian

**Comment by arcolinuxz** [comment]
Thanks for reporting

I have a video about it on how to solve it - just for isobuilders.

As a user you do not have to do anything - I will build new isos later.

We jumped from branch in Calamares - seems the variable declaration is different
