### ISSUE TITLE
Installation Failed: Bad unpack configuration: The source filesystem '/run/archiso/bootmnt/arch/x86_64/airootfs.sfs' does not exist

### ISSUE THREAD

**Issue by kamikaze211** [arch-linux-calamares-installer/alci-iso-zen#2]
![photo_2024-01-12_09-30-08](https://github.com/arch-linux-calamares-installer/alci-iso-zen/assets/16874290/f391e4e2-08de-421b-8f58-77b005bd1584)

On a virtual machine, these files are OK, because the iso is mounted correctly

![Screenshot_20240112_011953](https://github.com/arch-linux-calamares-installer/alci-iso-zen/assets/16874290/22d2793e-4f33-4b94-9a3a-286de3b66ea2)

But on a physical machine, the iso will not be mounted by default, and if I mount it by click, it will be mounted to /run/media/userlive/xxx

![photo_2024-01-11_21-16-23](https://github.com/arch-linux-calamares-installer/alci-iso-zen/assets/16874290/b68c7491-02a0-4fdc-88ca-b3e7cb0b0a6a)

So if I use alci to install, it will give me an error repot look like this

I'm not sure if this is my problem, can anyone help me?

**Comment by arcolinuxz** [comment]
Did you change anything to our github?

**Comment by kamikaze211** [comment]
> Did you change anything to our github?

I changed these files:

/archiso/pacman.conf ( only added an archlinuxcn repo )
/archiso/packages.x86_64 ( only changed to de to plasma )
/archiso/airootfs/etc/locale.conf (only changed the locale to Zh-cn )
/archiso/airootfs/etc/pacman.conf ( only deleted the alci repo )
/archiso/airootfs/etc/pacman.d/mirrorlist ( only changed to China mirror )

**Comment by arcolinuxz** [comment]
I build the iso here and got the same error

I guess it is broken

Will check it this week-end

**Comment by kamikaze211** [comment]
> I build the iso here and got the same error
> 
> I guess it is broken
> 
> Will check it this week-end

OK
Thank you for your hard working
Waiting for good news

**Comment by arcolinuxz** [comment]
solved and pushed the changes online
new isos going on sourceforge
check out the reason - it was easy if you follow the path then you see you are missing one folder in the path

**Comment by kamikaze211** [comment]
> solved and pushed the changes online new isos going on sourceforge check out the reason - it was easy if you follow the path then you see you are missing one folder in the path

Thank you my friend, I rebuilt it, and it works now.
